### ISSUE TITLE
Expose the advance search function of Aquarius

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/squid-py#125]
It would be necessary to expose in Squid-py the advanced search capabilities provided by Aquarius in the method:
`POST /api/v1/aquarius/assets/ddo/query`

This should be implemented in a generic way, allowing to use from squid-py different backends plugged into Aquarius (Mongodb, Elastic).

**Comment by ttmc** [comment]
We _could_ do that. It would amount to creating (and maintaining) a custom HTTP API wrapper around the search capabilities exposed by pymongo, elasticsearch-dsl, or other Python SDKs. Coding that would take developer time (i.e. salary money) and the end result would be some kind of lowest-common-denominator OceanDB search API.

If I'm a Marketplace developer using Python, I already have direct access to my MongoDB, Elasticsearch or whatever OceanDB database, and I can just use pymongo, elasticsearch-dsl, or other Python SDKs to get the full search power of that database. I'm not going to use some strictly-weaker indirect Aquarius HTTP API (or if I do, I'm going to be upset when I discover there's a better way).

Some highly-specialized searches might be useful to expose via the Aquarius HTTP API, especially ones that return either zero results or one result. Searches that can return pages of results are a pain to deal with and wrapping them in an HTTP API should be avoided.

**Comment by MarcusJones** [comment]
I raised this coming from data science mantaray perspective. It is likely that a data scientist would use an online marketplace, once this is in place. However, the current squid-py search function is too rudimentary to be useful, and mostly unimplemented; 

```python
    def search_assets_by_text(self, search_text):
        # TODO: implement this
        assets = []
        return assets
```

I would like to at least text search within a metadata field, currently the `text_search` method just sweeps the entire Metadata as a big string.

**Comment by ttmc** [comment]
I would say that it is the job of the Marketplace to expose (or not expose) advanced search on their database. They might do that, for example, by exposing their MongoDB database with some limited permissions. Or they might create their _own_ search API wrapper around their database.

We might implement some example marketplace search APIs, but we shouldn't be limiting what marketplaces can do.

**Comment by ssallam** [comment]
This task is completed.
