### ISSUE TITLE
Configuration fails on lowercase contract ABI paths

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#132]
```
FileNotFoundError: [Errno 2] No such file or directory: '~/anaconda3/envs/mantaray/artifacts/OceanAuth.Ocean_POA_AWS.json'
```
But the contract does exist in my environment; `oceanauth.ocean_poa_aws.json'

Possible Solution:

Iterate over each and find the contracts with a .to_lower comparison.

**Comment by ssallam** [comment]
This is fixed now.
