### ISSUE TITLE
AquariusWrapper.get_asset_metadata() returns DDO

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#151]
Generally, DDO and Meta Data need clear separation of terminology and implementation to avoid confusion. 

See i.e.: https://github.com/oceanprotocol/squid-py/blob/e0e08d6250b977d99e058be380f4d3f22af6b23a/squid_py/aquariuswrapper.py#L38

This method calls:
`/api/v1/aquarius/assets/ddo`

It should call: 
`/api/v1/aquarius/assets/metadata/{id}` 

Similarly, this method calls get_asset_metadata: 
Ocean.resolve_did()

### Possible Solution

Refactor get_asset_metadata(). 

Create a new method,  get_asset_ddo().

**Comment by ssallam** [comment]
Yes, this was in the plan, but because aquarius wrapper is meant to be internal to ocean, priority was low.

But I agree, this method must be renamed to avoid confusion.

**Comment by eruizgar91** [comment]
#169
