### ISSUE TITLE
Add documentation in the code to all the public and private methods

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/squid-py#154]
This documentation for each method should include:

- The intention of the method
- Input parameters and data types, data formats (i.e if is a did should include or not the `0x`)
- Output
- Exceptions raised in the code

**Comment by ttmc** [comment]
This issue is closely related to #153 because in Python, one documents a method's intention, inputs, outputs, exceptions, etc. using Python docstrings (i.e. special comments) and then those docstrings get used when generating the web-based documentation requested by issue #153. (Docstrings are also used by IDEs and other tools. Generating documentation isn't their only purpose.)

In short, to resolve issue #153, this issue (#154) must be resolved first, or at the same time.

**Comment by aaitor** [comment]
@ssallam , that should be well documented because users of the library could not be aware of this convention. This also should be discussed/standardised in all the squid implementations.

**Comment by aaitor** [comment]
@ttmc , agree. This issue is related but it's not the same. I think could be resolved in parallel.

**Comment by ttmc** [comment]
This issue could be titled, "Get all docstrings in good shape". I can help with that, but there's a lot of code in squid-py, so we need to agree on certain standards.

Looking at the docstrings that already exist in the squid-py code, it seems we are using [PEP 257](https://www.python.org/dev/peps/pep-0257/) standard docstrings (_not_ Google style docstrings and _not_ NumPy style docstrings). However, there are many deviations from [PEP 257](https://www.python.org/dev/peps/pep-0257/).

Therefore, as a starting point, please read [PEP 257](https://www.python.org/dev/peps/pep-0257/) and follow the standard. Departures from the standard lead to broken or less-useful documentation.

There are linters to check if docstrings follow PEP 257, e.g. https://github.com/dpursehouse/pep257 . Once we have the docstrings in reasonably good shape, we could use one of those (e.g. in Travis tests) to help us stick to PEP 257.

**Comment by ttmc** [comment]
Now that pull request #194 is merged, @eruizgar91 said that almost everything in squid-py has docstrings now, except for the code that @ssallam is refactoring.

**Comment by ssallam** [comment]
The class refactor is completed, docstrings updated/added.
Let's evaluate what we have and decide to whether to close this issue.

**Comment by aaitor** [comment]
@ssallam , can we close this one?

**Comment by ssallam** [comment]
Yes, this is good now, will update methods doc strings as we go.
