### ISSUE TITLE
New hex class for DID and addressses

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#170]
## Expected Behavior

A DID is a 256 bit string. This can have many representations, such as 0x prefixed hex string, or with did:op: etc..

Wallet addresses similarly. 

A hex string is only a base 16 convenience representation of this bit string. 

In any case, hex strings must be case insensitive. 

## Current Behavior

Inconsistent case, prefix behavior. 

### Possible Solution

New class to store 256 bit strings. Inherit or aggregate from the Bytes built-in. `@property` methods for context switching. Unit tests to enforce case - insensitivity.

**Comment by ttmc** [comment]
If you have a `bytes` object, you can (since Python 3.5) get the hex `str` (base 16) representation using [the hex() method](https://docs.python.org/3/library/stdtypes.html#bytes.hex) of the `bytes` object, e.g.
```python
>>> mybytes = b"\x12\xcc\xf0a"
>>> type(mybytes)
<class 'bytes'>
>>> mybytes.hex()
'12ccf061'
>>> type(mybytes.hex())
<class 'str'>
```
Going the reverse direction, from a hex `str` to a `bytes` object, is also easy, e.g.
```python
>>> mystr = "a1fa1fabe1"
>>> bytes.fromhex(mystr)
b'\xa1\xfa\x1f\xab\xe1'
```

**Comment by ssallam** [comment]
This is outdated now, please reopen or file a new issue if needed.
