### ISSUE TITLE
Add test examples (integration tests) in squid-py similar to examples in squid-js

### ISSUE THREAD

**Issue by JohnBDB** [oceanprotocol/squid-py#175]
The task here is to write examples as integration tests similar to the examples in squid-js.

**Comment by H34D** [comment]
example here: https://github.com/oceanprotocol/squid-js/tree/develop/src/examples

**Comment by aaitor** [comment]
Can we review if we can have the same approach in squid-py to the one that @H34D gave in his first link?

**Comment by ssallam** [comment]
Examples added for register and purchase asset. 
Examples needed for asset search and retrieval.
