### ISSUE TITLE
More modular and less complex unit tests

### ISSUE THREAD

**Issue by JohnBDB** [oceanprotocol/squid-py#182]
Squid-py unittests use the pytest framework.
Notes:
* There is already a `conftest.py` file which contain some useful fixtures:
  * Ocean instance: takes care of loading config, instantiating ocean instance, setting main account and password (from config file), and requesting ocean tokens. There are two different fixtures one for consumer and another for publisher role.
  * Registered DDO: checks for and registers an agreement template then registers a new asset DDO

The following is a list of specific tests that need refactor:
* `test_register_service_agreement` and `test_service_agreement`: 
  * Currently uses the unittest framework. Rewrite it to use pytest
* `test_sa_template` needs to test something
* `test_aquarius`: test each function separtely
* `test_assets`:
  * Remove `test_register_data_asset_market` since market is no longer used for this purpose
  * Test registering in the DIDRegistry keeper contract and verify did url attribute is registered and event emitted
* `test_connection`: seems to print info about running docker containers
  * This should be like a precondition to running the tests. 
  * It should also assert that the expected docker containers are running
* `test_keeper_contracts` needs more coverage
* `test_ocean`: add tests for 
  * encryption/decryption
  * consume asset
  * verify signature

**Comment by eruizgar91** [comment]
We need continue working on this issue.

**Comment by eruizgar91** [comment]
Pending of increase keeper-contracts coverage
