### ISSUE TITLE
DDO parsing and schema validation

### ISSUE THREAD

**Issue by JohnBDB** [oceanprotocol/squid-py#184]
It would be good to have explicit validation of ddo documents which can be used to verify ddo from different implementations of squid.

Implementation of this task is here:
https://github.com/oceanprotocol/Plecos

**Comment by MarcusJones** [comment]
Bump. 

Plecos should now be integrated as a dependency in squid-py. 

Replace `squid_py.ddo.metadata.Metadata.validate()` with `plecos.is_valid` and `plecos.list_errors()`.

Similarly, `.get_example` can reference a static file in Plecos.
