### ISSUE TITLE
Cross OS support in squid

### ISSUE THREAD

**Issue by JohnBDB** [oceanprotocol/squid-py#187]

**Comment by ssallam** [comment]
This is ambiguous.

**Comment by ttmc** [comment]
> This is ambiguous.

Indeed. Python code generally works on most common operating systems, but there are exceptions (e.g. some multiprocessing things don't work on macOS), so I guess we should check if squid-py code works on operating systems where people might want to use it? What operating systems might be on that list?

**Comment by H34D** [comment]
https://github.com/oceanprotocol/barge#prerequisites

**Comment by aaitor** [comment]
Can somebody provide more detailed information about the scope of this task? 
If not we will close it.
