### ISSUE TITLE
Resolve issues found by PyLint

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/squid-py#188]
Codacy uses PyLint to check Python code style (and related issues) and is currently reporting many problems with the squid-py codebase, but you don't have to rely on Codacy to use PyLint, you can install it locally and use it from the command line.

PyLint docs: https://pylint.readthedocs.io/en/latest/index.html 

Aitor said you can start by fixing the errors and fatal errors, since those are higher priority.

Bonus: We don't use Flake8, so for bonus points, feel free to remove all the Flake8 references from this repo.

**Comment by eruizgar91** [comment]
Most of the issues in Codacy are fixed, there are only pending that ones of the service-agreements refactor that is in a different issue #160.
