### ISSUE TITLE
Support absolute and relative paths for contract ABIs

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#221]
## Expected Behavior
Support absolute and relative paths for contract ABIs. I.e. `~/.ocean` for deployed artifacts from barge, `./artifacts` for custom artifacts, etc..

### Possible Solution
use the `'pathlib` module. 
```
from pathlib import Path
p1 = Path('/bin')
p2 = Path('bin')
p3 = Path('~/bin')
p1.is_absolute()
True
p2.is_absolute()
False
p3.expanduser()
PosixPath('/home/batman/bin')
```

**Comment by ssallam** [comment]
Sounds good, new behavior (in order):
* `keeper.path` if defined in config
  * Support both absolute and relative paths
* `venv/keeper-contracts/artifacts`
* `cwd/artifacts`

**Comment by MarcusJones** [comment]
Bump this, just ran into it again in Mantaray. A better name could be `abi_path`. 

The pathlib Path class is great for this stuff. 

Also, would be great to have the `abi_path` as an attribute on `Config` class.
