### ISSUE TITLE
Add @classmethod to Config() class for dict

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#226]
## Current Behavior

Instantiating config from dict requires 
```
configuration = Config(filename=None, options_dict=config_dict)
```

Cleaner would be to use an alternate constructor. 

### Possible Solution
```
@classmethod
    def from_dict(cls, confif_dict)
```

**Comment by ssallam** [comment]
Both args have default values in the constructor. 

To make a Config instance: `configuration = Config(options_dict=config_dict)`
