### ISSUE TITLE
Use Account() class for .main_account

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#227]
## Expected Behavior

What is the point of Account class if not for this? 

https://github.com/oceanprotocol/squid-py/blob/690d16b517777bf117e0e3f1b66a3347a633bb23/squid_py/ocean/ocean.py#L103

## Current Behavior

Account() is used for listing accounts, but not main account. 

### Possible Solution

Instantiate Account() for .main_account

**Comment by ssallam** [comment]
`main_account` has been removed in the latest  refactor. An account needs to be passed into ocean functions that require it.

**Comment by MarcusJones** [comment]
Clear thx.
