### ISSUE TITLE
Ocean.accounts = Ocean.get_accounts() is not needed in constructor

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#228]
## Current Behavior

https://github.com/oceanprotocol/squid-py/blob/690d16b517777bf117e0e3f1b66a3347a633bb23/squid_py/ocean/ocean.py#L94

### Possible Solution

Propose to move this out, it causes traffic and isn't necessary!

**Comment by ssallam** [comment]
This has changed. `ocean.accounts` is a submodule with a `list` method. `ocean.get_accounts()` is deprecated and delegates to `ocean.accounts.list()`
