### ISSUE TITLE
Account.request_token() returns Hex (reciept??), not bool

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#238]
https://github.com/oceanprotocol/squid-py/blob/e48b581f430a43201232d1120a950fb289bc44e1/squid_py/ocean/account.py#L48

Incorrect docstring in this method

**Comment by MarcusJones** [comment]
Should we include as an optional parameter `wait=False`
and 
```
if wait: 
    Web3Provider.get_web3().eth.waitForTransactionReceipt(rcpt) 
```
?

**Comment by ssallam** [comment]
The new method says it returns bool and it actually returns a bool.
