### ISSUE TITLE
`keeper.url` vs `parity.url` in config file -> unify to something like testnet_rpc.url?? 

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#255]
## Current Behavior

There are 2 entries in the configuration file for squid-py which are the same - 
```
[keeper-contracts]
keeper.url = https://nile.dev-ocean.com
keeper.path = artifacts

secret_store.url = https://secret-store.dev-ocean.com
parity.url = https://nile.dev-ocean.com
```

Is it necessary to have both of these? Is there a better name going forward?

**Comment by ssallam** [comment]
The two urls need to remain separate for now. 

`keeper.url` name makes sense, so I suggest not changing this

`parity.url` name can be improved, it is actually the url of the parity node for signing secretstore transactions. So the name could be something like `secretstore-signer.url`

**Comment by trentmc** [comment]
Given the previous comment, there's not much else to do. And, keepers will become obsolete with datatokens. Closing.
