### ISSUE TITLE
Create unify API as squid-js

### ISSUE THREAD

**Issue by eruizgar91** [oceanprotocol/squid-py#26]
## Expected Behavior
Move the logic currently in the provider to this project implementing and API as this https://github.com/oceanprotocol/dev-ocean/blob/feature/squid/doc/development/squid.md in a way that we expose the same methods in squid-js and squid-py.

**Comment by MarcusJones** [comment]
Merging with Issue #45 
https://github.com/oceanprotocol/squid-py/issues/45
