### ISSUE TITLE
Update web3 version to 5.0.0

### ISSUE THREAD

**Issue by eruizgar91** [oceanprotocol/squid-py#263]
Web3.py is close to release a version 5.0.0 with many changes. We should check the compatibility of this version with the current code and upgrade as soon as we can.

**Comment by ssallam** [comment]
* What is the priority and urgency of this upgrade?
* Is Web3 5.0.0 stable?

**Comment by ssallam** [comment]
Web3 py v5.x is in alpha mode.

**Comment by kieranslater** [comment]
is this any closer to happening? I am trying to run squid with other software that already uses 5.0.0b2, and I can't get to work together.

**Comment by kieranslater** [comment]
I have been trying to get to work with 5.0.0b2 but seem to be too many differences
