### ISSUE TITLE
Rename squid-py to ocean-py

### ISSUE THREAD

**Issue by ssallam** [oceanprotocol/squid-py#273]
The package name for squid-py in pypi does not relate to `ocean` well. Therefore it is suggested by some team members to rename squid-py to ocean-py or ocean-squid-py.

**Comment by kremalicious** [comment]
If we rename the "core" name we would need to sync it with `squid-js` & `squid-java` to avoid confusion. Since we use a namespace for js `@oceanprotocol/squid` I would suggest also using a namespace for the Python package, instead of e.g. `ocean-py`

**Comment by ssallam** [comment]
Yes, the intention is to update all.

**Comment by aaitor** [comment]
It's my personal opinion but I don't see the benefits of this. The product and packages are under the Ocean Protocol organization, so any user installing the library should know he/she is using Ocean.
In addition to this, it would require:
- Rename repos of all the implementations
- Update documentation + docs.oceanprotocol
- Amend existing OEPs, dev-ocean, etc
- Amend existing blog posts

Also there are already ocean-xxx repos in github controlled by DEX.

**Comment by MarcusJones** [comment]
So those are the benefits as I see them, but I agree it comes at a cost! One alternative approach could be to have a data-science specific package with squid-py as a dependency. I already have mantaray-utilities wrapping some squid-py.

**Comment by aaitor** [comment]
@MarcusJones , I think that's an implementation detail of python that shouldn't affect the naming of a project. For example in java the way to interact is adding a dependency of the library and instantiating the class:

```xml
        <!-- Ocean Protocol Squid library: Includes Web3j and keeper stubs & ABI's -->
        <dependency>
            <groupId>com.oceanprotocol</groupId>
            <artifactId>squid</artifactId>
            <version>0.1.0</version>
        </dependency>
```

```java
import com.oceanprotocol.squid.*;

[...]

OceanAPI oceanAPIFromConfig = OceanAPI.getInstance(config);
```

In JS:
```js
const { Ocean, Logger } = require('@oceanprotocol/squid')
```

**Comment by ssallam** [comment]
I'm closing this since we don't have agreement.
