### ISSUE TITLE
When testing asset buy, MockBrizo is using the consumer address to execute the SLA

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/squid-py#283]
## Prerequisites

Squid-py v0.3.2

## Expected Behavior
Expect MockBrizo to be started up using the publisher address, not the consumer address

## Failure Information (for bugs)

The 'from' address `0x068ed00cf0441e4829d9784fcbe7b9e26d4bd8d0` is the consumer address.

> ocean - DEBUG - initializeAgreement receipt AttributeDict({'blockHash': HexBytes('0x74e97cdaeff052ac1a2072ddecb3dc860d8fd31e15625c1c1a5b36c3b90184c0'), 'blockNumber': 4896, 'contractAddress': None, 'cumulativeGasUsed': 437307, 'from': '0x068ed00cf0441e4829d9784fcbe7b9e26d4bd8d0', 'gasUsed': 405388, 'logs': [AttributeDict({'address': '0x3B10F48eB26792A19B49A40B4F89d01150733854', 'blockHash': HexBytes('0x74e97cdaeff052ac1a2072ddecb3dc860d8fd31e15625c1c1a5b36c3b90184c0'), 'blockNumber': 4896, 'data': '0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000068ed00cf0441e4829d9784fcbe7b9e26d4bd8d0000000000000000000000000068ed00cf0441e4829d9784fcbe7b9e26d4bd8d0', 'logIndex': 1, 'removed': False, 'topics': [HexBytes('0x01eacc668deaba202ffe441b3d9574c96eec55fb4bac58ee980a0fefff4f7501'), HexBytes('0x40bbb616af4a49c7af81d8bf64f2a4ec35f2bd47295946cdb91a4dd3cd5d9a56'), HexBytes('0xb7c22b1215ccb2f172c98d0e67d09c74f75b6c196ec17591e3d5d5b95cd95504'), HexBytes('0x7345ed337eb24b128bae0c9baf4b40d73cb95bc173e84c3bb31285cb7d98e115')], 'transactionHash': HexBytes('0xe22047b8a3dc432b34ddc16aaef32d055d49a648a7ad3f0fd84b1edeeb0e259c'), 'transactionIndex': 1, 'transactionLogIndex': '0x0', 'type': 'mined'}), AttributeDict({'address': '0x3B10F48eB26792A19B49A40B4F89d01150733854', 'blockHash': HexBytes('0x74e97cdaeff052ac1a2072ddecb3dc860d8fd31e15625c1c1a5b36c3b90184c0'), 'blockNumber': 4896, 'data': '0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000068ed00cf0441e4829d9784fcbe7b9e26d4bd8d0000000000000000000000000068ed00cf0441e4829d9784fcbe7b9e26d4bd8d0', 'logIndex': 2, 'removed': False, 'topics': [HexBytes('0x01eacc668deaba202ffe441b3d9574c96eec55fb4bac58ee980a0fefff4f7501'), HexBytes('0x40bbb616af4a49c7af81d8bf64f2a4ec35f2bd47295946cdb91a4dd3cd5d9a56'), HexBytes('0x80137081444bba61770256cb5ff483320f63af81dbc954c6d322e71b943a9455'), HexBytes('0x7345ed337eb24b128bae0c9baf4b40d73cb95bc173e84c3bb31285cb7d98e115')], 'transactionHash': HexBytes('0xe22047b8a3dc432b34ddc16aaef32d055d49a648a7ad3f0fd84b1edeeb0e259c'), 'transactionIndex': 1, 'transactionLogIndex': '0x1', 'type': 'mined'}), AttributeDict({'address': '0x3B10F48eB26792A19B49A40B4F89d01150733854', 'blockHash': HexBytes('0x74e97cdaeff052ac1a2072ddecb3dc860d8fd31e15625c1c1a5b36c3b90184c0'), 'blockNumber': 4896, 'data': '0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000068ed00cf0441e4829d9784fcbe7b9e26d4bd8d0000000000000000000000000068ed00cf0441e4829d9784fcbe7b9e26d4bd8d0', 'logIndex': 3, 'removed': False, 'topics': [HexBytes('0x01eacc668deaba202ffe441b3d9574c96eec55fb4bac58ee980a0fefff4f7501'), HexBytes('0x40bbb616af4a49c7af81d8bf64f2a4ec35f2bd47295946cdb91a4dd3cd5d9a56'), HexBytes('0x7ea643b9dd05147132a8c7da19995c273ce3b6e699b3299738522faecb40a9c9'), HexBytes('0x7345ed337eb24b128bae0c9baf4b40d73cb95bc173e84c3bb31285cb7d98e115')], 'transactionHash': HexBytes('0xe22047b8a3dc432b34ddc16aaef32d055d49a648a7ad3f0fd84b1edeeb0e259c'), 'transactionIndex': 1, 'transactionLogIndex': '0x2', 'type': 'mined'}), AttributeDict({'address': '0x3B10F48eB26792A19B49A40B4F89d01150733854', 'blockHash': HexBytes('0x74e97cdaeff052ac1a2072ddecb3dc860d8fd31e15625c1c1a5b36c3b90184c0'), 'blockNumber': 4896, 'data': '0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000068ed00cf0441e4829d9784fcbe7b9e26d4bd8d0000000000000000000000000068ed00cf0441e4829d9784fcbe7b9e26d4bd8d0', 'logIndex': 4, 'removed': False, 'topics': [HexBytes('0x01eacc668deaba202ffe441b3d9574c96eec55fb4bac58ee980a0fefff4f7501'), HexBytes('0x40bbb616af4a49c7af81d8bf64f2a4ec35f2bd47295946cdb91a4dd3cd5d9a56'), HexBytes('0x4e29479771585cf33b1d2d01a268a880d861d13259bb3c907b6c8748e5a07e32'), HexBytes('0x7345ed337eb24b128bae0c9baf4b40d73cb95bc173e84c3bb31285cb7d98e115')], 'transactionHash': HexBytes('0xe22047b8a3dc432b34ddc16aaef32d055d49a648a7ad3f0fd84b1edeeb0e259c'), 'transactionIndex': 1, 'transactionLogIndex': '0x3', 'type': 'mined'}), AttributeDict({'address': '0x3B10F48eB26792A19B49A40B4F89d01150733854', 'blockHash': HexBytes('0x74e97cdaeff052ac1a2072ddecb3dc860d8fd31e15625c1c1a5b36c3b90184c0'), 'blockNumber': 4896, 'data': '0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000068ed00cf0441e4829d9784fcbe7b9e26d4bd8d0000000000000000000000000068ed00cf0441e4829d9784fcbe7b9e26d4bd8d0', 'logIndex': 5, 'removed': False, 'topics': [HexBytes('0x6d738d7f26a48a4aec3d4c3508d59e95b88978d249033a6d3379b4689b64fc1c'), HexBytes('0x40bbb616af4a49c7af81d8bf64f2a4ec35f2bd47295946cdb91a4dd3cd5d9a56'), HexBytes('0x044852b2a670ade5407e78fb2863c51de9fcb96542a07186fe3aeda6bb8a116d'), HexBytes('0x7345ed337eb24b128bae0c9baf4b40d73cb95bc173e84c3bb31285cb7d98e115')], 'transactionHash': HexBytes('0xe22047b8a3dc432b34ddc16aaef32d055d49a648a7ad3f0fd84b1edeeb0e259c'), 'transactionIndex': 1, 'transactionLogIndex': '0x4', 'type': 'mined'})], 'logsBloom': HexBytes('0x00000000000000000000000000008000000080000000000000000000000000000000000000000000000000000000000000000000000000000000080002000000002000000000000000001000010000002000000008000000000000008000800000000000002000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000004000000000800000000000000000000000000000000000000002020000000020000000000000000000000800800000000080000000800000000000000000000000000000000040000000000120000000000000000000000000000000000000600000000000000000001010000'), 'root': None, 'status': 1, 'to': '0x3b10f48eb26792a19b49a40b4f89d01150733854', 'transactionHash': HexBytes('0xe22047b8a3dc432b34ddc16aaef32d055d49a648a7ad3f0fd84b1edeeb0e259c'), 'transactionIndex': 1})
2019-02-04 15:06:30,051 - ocean - DEBUG - Success initializing service agreement 0x40bbb616af4a49c7af81d8bf64f2a4ec35f2bd47295946cdb91a4dd3cd5d9a56, got status 1

## Step to Reproduce the problem
python -m pytest tests/ocean/test_buy_asset.py -s

**Comment by eruizgar91** [comment]
Fixed in v0.4.2
