### ISSUE TITLE
Move configuration information to library parameters

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/squid-py#29]
## Expected Behavior
This a 'library' and so all setup and config values should be passed to the library, as parameters, by the calling client code or by the testing code. 

The configuration values are:

*current config name, environment variable name*

1. keeper.host, KEEPER_HOST
1. keeper.port, KEEPER_PORT
1. provider.uri, PROVIDER_URI ( should this be: provider_url, PROVIDER_URL?)
1. market.address, MARKET_ADDRESS
1. auth.address, AUTH_ADDRESS
1. token.address, TOKEN_ADDRESS
1. contracts.folder, CONTRACTS_FOLDER
1. gas.limit, GAS_LIMIT

## Current Behavior

Accessing config information is embedded within the library, via the config_parse.py module.

## Possible Solution

1. Pass the configuration information listed above as individual items to the ```Ocean.__init__```
1. For compatibility pass a configuration file that can be read within the ```Ocean.__init__``` ,  and so read and set the configuration values in one place.
1. Remove references to ```get_value``` and ```config``` within classes in the library, and pass the actual configuration values instead.
1. Move configuration loading to the tests folder, so that the test suite reads a configuration file.

**Comment by ssallam** [comment]
* 2., 3. (+1) 
* 1. > Instead of passing individual values, pass a dict (kwargs)

**Comment by billbsing** [comment]
+ nr 1  yes to provide via kwargs
+ nr 2 for compatibility, but getting all config values in the ```__init__```
+ nr 3 to remove, finding out where config values are used in the API is currently a nightmare.. opportunity for errors
