### ISSUE TITLE
Failure on `ocean_assets.order()`

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#297]
## Current Behavior

`ocean_assets.order()` is broken. I think during the call to ddo.asdictionary(), the type of the service ID changes from int to string. 

Below `if` condition fails. 

Need unit test coverage on this method! 

## Failure Information (for bugs)
```
    def find_service_by_id(self, service_id):
        service_id_key = 'serviceDefinitionId'
        for s in self._services:
            if service_id_key in s.values and s.values[service_id_key] == service_id:
                return s

        return None
```

### Possible Solution
`            if service_id_key in s.values and int(s.values[service_id_key]) == service_id:`

## Specifications
squid-py == 0.4.2

**Comment by ssallam** [comment]
Fixed.
