### ISSUE TITLE
`ocn.assets.order(this_asset.did, '0', consumer_acct)` to accept 'access' as string

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#298]
## Current Behavior

The param `service_definition_id` is not clear for end users of the high level API. Propose to change to use the actual string of the service type = 'access'. 

### Possible Solution

`order(self, did, service_type, consumer_account)`

Ref issue #297

**Comment by ssallam** [comment]
The change in above PR allows using service type in `ocean.assets.order` but does not change the parameter name. So it accepts either the id or type.

**Comment by ssallam** [comment]
@MarcusJones can you please verify whether the solution meets expectations.

**Comment by MarcusJones** [comment]
Closed by #302
