### ISSUE TITLE
Download with progress bar / logging

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#299]
## Current Behavior

Downloading a large asset shows no progress or logging. How will users know that their asset was successfully purchased? 

### Possible Solution

Progress bar in python i.e. https://pypi.org/project/tqdm/ or at least some logging feedback, ie;

`asset download started, 56 MB`

`asset download 10%` 

`asset download complete, stored in /path/to/file`

etc...

**Comment by eruizgar91** [comment]
Close by #303
