### ISSUE TITLE
List of Ethereum accounts from the Ocean class

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/squid-py#30]
## Expected Behavior

The ```ocean``` class to return a list of Ethereum accounts. 
This is a wrapper around the ```web3_helper.accounts``` module, since the calling client does not need to use or see any reference to web3.

## Current Behavior

Currently you need to use the ```utils.web3_helper.py``` module, to get a list of web3 accounts.

**Comment by ssallam** [comment]
There will be an `Accounts` module to handle all account related functions.

**Comment by billbsing** [comment]
I will keep this issue open, as the last PR does not completely solve this issue. Currently I return a address dict instead of an object
