### ISSUE TITLE
Can't register free assets (price = 0)

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#309]
This is a fun one. 

In `metadata.py` `.validate()`, the following section errors; 
```
            section = Metadata.MAIN_SECTIONS[section_key]
            section_metadata = metadata[section_key]
            for subkey in section.REQUIRED_VALUES_KEYS:
                if subkey not in section_metadata or not section_metadata[subkey]:
                    print("ERROR ON", subkey)
                    return False
```

With `squid_py.exceptions.OceanInvalidMetadata: Metadata seems invalid. Please make sure the required metadata values are filled in.`

The second part of the conditional, `not section_metadata[subkey]`, fails for an attribute set to `0`, since `0` is False. Hence price=0 is not allowed. 

Can tie into fixing with #308 .

**Comment by eruizgar91** [comment]
It will be close with #310
