### ISSUE TITLE
Move/ rename the Metadata Class to be the Asset Class

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/squid-py#32]
## Expected Behavior

Since Metadata is a data type structure that can be used by any other type of class of object, it would be better to arrange the library classes around an Asset, Service, Compute or any type of class within the Ocean network.

The Metadata class maybe re-introduced as an object returned or used by the Asset class, for the register/update methods.

1. Move the ```get_assets``` to the Ocean class. 
1. Move the ```register_asset``` to the Ocean class. Returns an Asset Object
1. Move the ```get_asset_ddo``` to the Ocean class and rename as ```get_asset```. Allow for DID or asset_id to be passed to get the asset, return an Asset object or None if not found.

Rename the Metadata class to be the Asset class, and rename the methods:
1. Rename ```get_assets_metadata``` to ```get_metadata(self)```
1.Rename ```update_asset(self, data)``` to ```update(self, data)```
1.Rename  ```retire_asset(self, asset_id)``` to ```retire(self)```

**Comment by ssallam** [comment]
Good stuff. Keep in mind the squid interface is still being defined. The `Trilobite` version is not finalized yet.

**Comment by MarcusJones** [comment]
Resolved. Asset aggregates the DDO class, which in turn contains MetaData.
