### ISSUE TITLE
Add a Credit Ocean Token method to the Ocean class ( for Development )

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/squid-py#34]
## Expected Behavior

Add a ```credit(self, account_id, amount)``` method to the Ocean class, so that the library user can credit their account with ocean tokens.

**Comment by ssallam** [comment]
Any additions, updates, etc. to the squid lib should reference the common squid interface defined in `https://github.com/oceanprotocol/dev-ocean/blob/feature/squid/doc/development/squid.md`
