### ISSUE TITLE
Possible misuse of Mock Brizo in testing

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/squid-py#371]
I've been looking at the squid-py tests and I have found a few low level 'issues' with the usage of MockBrizo. This could potentially cause problems later on with users of this library.

## use_brizo_mock=False still works
The following fixtures in conftest.py will work, even when the travis tests specify not to run brizo on the local network.

```python
@pytest.fixture
def publisher_ocean_instance_brizo():
    return get_publisher_ocean_instance(use_brizo_mock=False)


@pytest.fixture
def consumer_ocean_instance_brizo():
    return get_consumer_ocean_instance(use_brizo_mock=False)
```
This stil works beacuse an earlier test script within the test suite, has asked to use the MockBrizo object, instead of an external brizo server. So the BrizoProvider has already been assigned and so will be used until the end of the test.

## MockBrizo is assigned but not created
The call `ocean.assets.order` requires brizo or MockBrizo to be running, and listening for events with the `register_service_agreement_publisher` command. Only when the first call to `BrizoProvider.get_brizo()`  is called then the call to `ocean.assets.order` will work.

Currently the only reason the test **tests/ocean/test_buy_assets.py** works is that another test earlier has called `BrizoProvider.get_brizo()`

**Comment by ssallam** [comment]
Tests no longer rely on Brizo, instead each test handles it's own web3 events explicitly
