### ISSUE TITLE
ocean.agreements.subscribe_events will occasionally fail with an exception

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/squid-py#380]
## Expected Behavior
MockBrizo is listening for an agreement event to be raised by the consumer.

When the event is detected MockBrizo calls `register_service_agreement_publisher`.

## Current Behavior
When the error occurs, the consumers agreement is not correctly processed by MockBrizo, and so the asset_buy test fails

## Failure Information (for bugs)
```
travis-job-7c149e18-6842-48e6-ad75-a6417ab8c01b squid_py.keeper.multi_event_listener[6769] DEBUG Error processing event: {'code': -32016, 'message': 'The execution failed due to an exception.'}
```

## Step to Reproduce the problem
Run squid-py travis a few times to  buy an asset.

### Possible Solution
Web3 or request is thread safe?

## Specifications
squid-py v0.6.5

## BrizoMode Handler

```python
    def _handle_agreement_created(self, event, *_):
#        print('_handle_agreement_created ', event)
        if not event or not event.args:
            print('no handle created')
            return

        self._is_event_subscribed = True
        print(f'Start handle_agreement_created: event_args={event.args}')
        config = ConfigProvider.get_config()
        ocean = self._ocean_instance
        provider_account = self._account
        assert provider_account.address == event.args['_accessProvider']

        did = id_to_did(event.args['_did'])
        agreement_id = Web3Provider.get_web3().toHex(event.args['_agreementId'])

        ddo = ocean.assets.resolve(did)
        sa = ServiceAgreement.from_ddo(ServiceTypes.ASSET_ACCESS, ddo)

        condition_ids = sa.generate_agreement_condition_ids(
            agreement_id=agreement_id,
            asset_id=add_0x_prefix(did_to_id(did)),
            consumer_address=event.args['_accessConsumer'],
            publisher_address=ddo.publisher,
            keeper=Keeper.get_instance())

        register_service_agreement_publisher(
            config.storage_path,
            event.args['_accessConsumer'],
            agreement_id,
            did,
            sa,
            sa.service_definition_id,
            sa.get_price(),
            provider_account,
            condition_ids
        )
```

**Comment by billbsing** [comment]
If any one is reading this.. I believe I have found the problem. This error may also occur with an overworked Brizo server as well. Since Brizo also uses this same code.

The problem occurs in the line
```python
ddo = ocean.assets.resolve(did)
```
and potentially also in keeper calls to ethereum net via web3.py ( as Keeper is currently a static object).

The call `resolve` calls a static object `AquariusProvider`, this in turn calls `Aquarius` class that uses a cached request session to get the DDO from Aquarius. 

Since this call is being used within a thread the cached session has been created outside of the thread, so when another process also requests data from Aquarius at the same time it will also use the same cached session as the thread... and so we have a conflict & exception error.

Possible Solutions:

1. Some sort of locking so that the any thread gets a request session that is locked for that thread.
2. Pass an optional request session with the command `resolve`.
3. `Aquarius` class creates a new request session for each call, and so therefore for each thread.

**Comment by ssallam** [comment]
This code was completely refactored.
