### ISSUE TITLE
Metadata Parser / Validator

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#47]
## Expected Behavior

Implement a **metadata validator** to ensure compliance with https://github.com/oceanprotocol/OEPs/tree/feature/oep-08-links/8. 

## Current Behavior

No way to check if valid until attempting publish. 

### Possible Solution

Use i.e. https://json-schema.org/ to create a schema compliant with OEP8. 

Script to be run on single or multiple JSON files. 

The JSON files are not the DDO JSON. They are only the Metadata section of the DDO, which can then be inserted into the JSON tree upon instantiation of Assets. 

## Specifications

* Python: 3

**Comment by eruizgar91** [comment]
It would be implemented in this repo https://github.com/oceanprotocol/Plecos
