### ISSUE TITLE
Support dataset management, data seeding, end - end use case

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#77]
## Expected Behavior

The problem: Let's say I have 10 assets (datasets to keep it simple). These assets are stored locally on my machine in following folder structure;

```
├── British_birdsong
│   └── full
│       ├── birdsong_metadata.csv
│       └── songs.zip
├── Humpback_fluke_location
│   ├── full
│   │   └── cropping.txt
│   └── sample
│       └── cropping.txt
├── Humpback_identification
│   ├── full
│   │   ├── train.csv
│   │   └── train.zip
│   ├── metadata.json
│   ├── preview
│   │   ├── cover.jpg
│   │   └── discover.json
│   └── sample
│       ├── sample.zip
│       └── sample.csv
├── Monkey_Species
│   └── full
│       ├── monkey_labels.txt
│       ├── training.zip
│       └── validation.zip
etc...
```

So each **dataset** is stored in it's own directory. As a data owner, I have manually created or separated the files into 3 main directories:
 - full, for the main data set which I wish to place in an Ocean marketplace for purchase
 - sample, for a small free sample of the data
 - preview, (in case we support discovery with a banner image)

Assume that I can upload these files to i.e. S3 and save the public URLs. 

Given this, assume also that I can fully define the metadata locally, as follows (example); 

```
"base": {
  "name": "Humpback Whale Identification",
  "type": "dataset",
  "description": "This training data contains thousands of images of humpback whale flukes. Individual whales have been identified by researchers and given an Id. The challenge is to predict the whale Id of images in the test set. What makes this such a challenge is that there are only a few examples for each of 3,000+ whale Ids.",
  "size": "271.9mb",
  "dateCreated": "2018-06-25T00:00:000Z",
  "author": "Kaggle",
  "license": "CC0: Public Domain",
  "copyrightHolder": "Kaggle",
  "compression": "zip",
  "contentType": "jpg/csv",
  "workExample": "",
  "contentUrls": [
    "https://s3.eu-central-1.amazonaws.com/trilobite/Humpback_identification/full/train.csv",
    "https://s3.eu-central-1.amazonaws.com/trilobite/Humpback_identification/full/train.zip"
  ],
  "links": [
    {
      "name": "Sample of Asset Data",
      "type": "sample",
      "url": "https://s3.eu-central-1.amazonaws.com/trilobite/Humpback_identification/sample/sample.zip"
    },
    {
      "name": "Discovery Banner",
      "type": "discover",
      "url":  "https://s3.eu-central-1.amazonaws.com/trilobite/Humpback_identification/discover/cover.jpg"
    }
    {
      "name": "Discovery Data",
      "type": "discover",
      "url":  "https://s3.eu-central-1.amazonaws.com/trilobite/Humpback_identification/discover/discover.json"
    }

  ],
  "inLanguage": "en",
  "tags": "whale, kaggle, oceanography, classification",
  "price": -1
},
"curation": {
  "rating": 0,
  "numVotes": 0,
  "schema": "Binary Voting"
}
```

How can / should squid-py support my workflow: 
1. Validate my metadata for internal consistency #47 
1. Validate my S3 (azure, etc.) links to ensure they are up and running
1. Generate a DDO json, (from template?)
1. Insert my metadata.json into the DDO? 
1. Allow me to choose access control permissions? 
1. Allow me to easily update with new metadata, change permissions, price, etc.

## Current Behavior

Creating metadata and DDO manually, management scripts in Mantaray, and low level Squid-api calls.

**Comment by billbsing** [comment]
I would think items 1 & 2 are validation and assembly of an asset, such as building the meta data, selecting the files to use and validating the files and metadata structure. 

I'm not sure if we keep only basic validation in squid-py and the full asset assembly/validation as a separate set of library tools. 

Maybe for the time being we start doing this in squid-py and we can always move this section out to a different project ( nursery-squid-py ? )

Items 3 & 4 we have already implemented in squid-py, with the DDO library, so we do not need DDO templates , we can generate full DDO and add any data to the service record. 

See code for the creation of an asset using just the metadata: 
```python
    @classmethod
    def create_from_metadata(cls, metadata, service_endpoint):
        """return a new Asset object from a metadata dictionary"""
        # calc the asset id
        asset_id = hashlib.sha256(json.dumps(metadata['base']).encode('utf-8')).hexdigest()
        # generate a DID from an asset_id
        new_did = id_to_did(asset_id)
        # create a new DDO
        new_ddo = DDO(new_did)
        # add a signature
        private_password = new_ddo.add_signature()
        # add the service endpoint with the meta data
        new_ddo.add_service('Metadata', service_endpoint, values={'metadata': metadata})
        # add the static proof
        new_ddo.add_proof(0, private_password)
        # create the asset object
        this_asset = cls(ddo=new_ddo)
        logging.debug("Asset {} created from metadata {} ".format(this_asset.asset_id, metadata))
        return this_asset
```

Item 5 I'm hoping that the control permissions and price are set, when the asset is sent to _brizo server_.

This is why I have been questioning the use of update and adding the price/control information in the metadata. We should have a specific divide between static asset data and market data. See below..

I think there are two types of update of an Asset.

1. Update core metadata, the file contents has changed or the asset description, e.t.c. Then a new asset is created, with a new hash of the metadata. So this "update" would be creating a new asset.

1. Update the price, access control. The asset data is the same, but the type of access/price has changed. Not sure if this is addressed in the OEP's but we should get squid-py to update this information as a separate record with the _brizio server_, not part of the metadata.

**Comment by shark8me** [comment]
I'll second Bill's suggestion that this functionality should be kept out of squid-py. 
A library should support the "do one thing, do it well" maxim. 

Ideally there should be separate libraries (or namespaces with the same library), to:

* Generate metadata given a directory structure 
  * For this particular point, examples with a given library be useful. Every domain will have a different way to structure data+metadata (e.g. [COCO](http://cocodataset.org/#home), which has folders containing image files, each of which is an instance). We could provide library implementations support types of such data. 
* Validate the metadata given a particular schema.
* Generate a sample dataset . 

We could start with implementing such a library, then explore how it can integrate with Squid. (Technically, it doesn't need to, but it might be nice syntactic sugar).

**Comment by MarcusJones** [comment]
This will be implemented in `mantaray` as a utility tool.
