### ISSUE TITLE
Account.balance raises confusion

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#94]
## Expected Behavior

Explicit balance, or always ensure that balance is updated. 

## Current Behavior

Call 
```
Account.request_tokens(50)
```
Then check the balance: 
```
Account.balance.ocn
= 0? 
```

This is confusing, should be explicit.

Are these now outdated? 

```
    @property
    def ether_balance(self):
        """
        Call the Token contract method .web3.eth.getBalance()
        :return: Ether balance, int
        """
        return self.keeper.token.get_ether_balance(self.address)

    @property
    def ocean_balance(self):
        """
        Call the Token contract method .balanceOf(account_address)
        :return: Ocean token balance, int
        """
        return self.keeper.token.get_token_balance(self.address)
``` 
???

## Failure Information (for bugs)

This is called only on __init__:
```self.balance = self.get_balance()```

### Possible Solution

Add balance as @property method. 

Or _balance

Generally refactor the Account obj. 

## Specifications

* Version: 0.2.5

**Comment by ssallam** [comment]
This is already addressed.
