### ISSUE TITLE
ocean.register(asset)

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#98]
## Expected Behavior

Conform to API. 

## Current Behavior

ocean.register_asset(self, metadata, publisher_address, service_descriptors, threshold=None)

Lots of low-level operations in the method. 

Why are we building DDO inside this method? 

### Possible Solution

Use the Asset class. Separate the scope. 

As a data owner, I would typically build up an Asset locally before publishing. The Asset class aggregates the DDO object. Therefore, building the DDO is critical to building an Asset. 

## Specifications

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version: 0.2.5

**Comment by mikera** [comment]
It's not clear that the network needs to do anything at the point of asset registration, at least in the case of typical off-chain assets. This should be possible simply with something like (pseudocode):

```
asset = matketAgent.registerAsset(assetMetadata)
```

We have this working in the Reference Marketplace already. Happy to discuss further if helpful.

**Comment by aaitor** [comment]
In Squid, the intention `registerAsset` method is intended to create an Asset in the system given the Asset metadata. It's the intention of the current implementation to hide the complexity of:
* Create a DDO
* Encrypt the contentUrl's using the encryption/authorization system (in Trilobite the Secret Store)
* Store off-chain using the Metadata API
* Register the DID

It's not convenient to expose those low level functions to the final user. Each user of the library would need to implement those steps what is prone to errors, problems building the DDO (SA conditions for example), etc.

So the current implementation in 3 languages is aligned with the scope. Further releases could add additional decorators for the register asset function.
